apiVersion: project.openshift.io/v1
kind: Project
metadata:
  labels:
    kubernetes.io/metadata.name: kdump-pmem-setup
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.34
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.34
    security.openshift.io/scc.podSecurityLabelSync: "false"
  name: kdump-pmem-setup