apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocp4-kdump-pmem-setup-crb
  namespace: kdump-pmem-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ocp4-kdump-pmem-setup-sa
  namespace: kdump-pmem-setup